### ISSUE TITLE
您好，有些问题想向您请教一下

### ISSUE THREAD

**Issue by bukeyijuanjuan** [Arktis2022/Skip-TS#1]
在您的论文中，您在计算损失函数Lmac时是将每个异常图通过双插值的方式将每个异常图上采样到最大异常图尺寸，可是在您的代码中是
def loss_fucntion_2(a, b):  # 输入两个张量数组
    mse_loss = torch.nn.MSELoss()
    # 将a2和b2上采样得到的结果和a1、b1没上采样得到的结果比较
    a2 = F.interpolate(a[2], size=32, mode='bilinear', align_corners=True)
    b2 = F.interpolate(b[2], size=32, mode='bilinear', align_corners=True)
    l2 = torch.mean(mse_loss(a2.view(a2.shape[0], -1), b2.view(b2.shape[0], -1)))
    l1 = torch.mean(mse_loss(a[1].view(a[1].shape[0], -1), b[1].view(b[1].shape[0], -1)))
    loss2_1 = torch.abs(l2-l1)
    
    # 将a1和b1上采样得到结果，与a0和b0没上采用得到的结果比较
    a1 = F.interpolate(a[1], size=64, mode='bilinear', align_corners=True)
    b1 = F.interpolate(b[1], size=64, mode='bilinear', align_corners=True)
    l1 = torch.mean(mse_loss(a1.view(a1.shape[0], -1), b1.view(b1.shape[0], -1)))
    l0 = torch.mean(mse_loss(a[0].view(a[0].shape[0], -1), b[0].view(b[0].shape[0], -1)))
    loss2_2 = torch.abs(l1-l0)
    
    
    #print(loss2_1,loss2_2)
    #sys.exit()
    loss2 = loss2_1+loss2_2
    return loss2
作为科研小白，想向您提出两个小问题，烦望您作出指导：
1.在代码中是a[2]和b[2]上采样到32，a[1]和b[1]上采样到64，仿佛没有都上采样到最大异常图尺寸
2.在论文中是有三个Lmac差值加和得到Loss2，可是代码中只有两个结果的加和
希望您做出一定指导，非常感谢

**Comment by Arktis2022** [comment]
过段时间我会重新整理一下代码上传一份新的版本，再回答你的问题，最近比较忙，不好意思哈

**Comment by Arktis2022** [comment]
> 在您的论文中，您在计算损失函数Lmac时是将每个异常图通过双插值的方式将每个异常图上采样到最大异常图尺寸，可是在您的代码中是 def loss_fucntion_2(a, b): # 输入两个张量数组 mse_loss = torch.nn.MSELoss() # 将a2和b2上采样得到的结果和a1、b1没上采样得到的结果比较 a2 = F.interpolate(a[2], size=32, mode='bilinear', align_corners=True) b2 = F.interpolate(b[2], size=32, mode='bilinear', align_corners=True) l2 = torch.mean(mse_loss(a2.view(a2.shape[0], -1), b2.view(b2.shape[0], -1))) l1 = torch.mean(mse_loss(a[1].view(a[1].shape[0], -1), b[1].view(b[1].shape[0], -1))) loss2_1 = torch.abs(l2-l1)
> 
> ```
> # 将a1和b1上采样得到结果，与a0和b0没上采用得到的结果比较
> a1 = F.interpolate(a[1], size=64, mode='bilinear', align_corners=True)
> b1 = F.interpolate(b[1], size=64, mode='bilinear', align_corners=True)
> l1 = torch.mean(mse_loss(a1.view(a1.shape[0], -1), b1.view(b1.shape[0], -1)))
> l0 = torch.mean(mse_loss(a[0].view(a[0].shape[0], -1), b[0].view(b[0].shape[0], -1)))
> loss2_2 = torch.abs(l1-l0)
> 
> 
> #print(loss2_1,loss2_2)
> #sys.exit()
> loss2 = loss2_1+loss2_2
> return loss2
> ```
> 
> 作为科研小白，想向您提出两个小问题，烦望您作出指导： 1.在代码中是a[2]和b[2]上采样到32，a[1]和b[1]上采样到64，仿佛没有都上采样到最大异常图尺寸 2.在论文中是有三个Lmac差值加和得到Loss2，可是代码中只有两个结果的加和 希望您做出一定指导，非常感谢

你好，我近期整理了一下代码上传了最新版本。1. 最大异常图尺寸对应M1的尺寸，大小是64，所以在计算loss时都上采样到64即可； 2. 之前的代码是开发中的模型，更新代码中是三个Lmac损失的加和
